### ISSUE TITLE
Missing some nice to have files (xmlsocket, zlib and log.php)

### ISSUE THREAD

**Issue by IcedEagle** [TinoDidriksen/pjj-chats#6]
Hi Tino!

I'm in the process of setting up an internal fork I made of pjj-chats, and overall I got it working pretty smoothly at this point! There's some files though that don't appear to be in the depot, that would be nice to have as from what I understand, might give a slightly better user experience.

Missing files:
- common/zlib.php
- common/xmlsocket/* (specifically worker.php, but presuming others in this directory are needed)
- common/zlib.php

Any chance you would be willing to upload these? My fork seems to be working generally, but I'm assuming the XMLSocket would make refreshing either faster, or require less browser refreshes? Either way, would be great to have!

Thanks a bunch in advance!

**Comment by TinoDidriksen** [comment]
Done. `zlib.php` is useful.

`xmlsocket` less so. It uses a client-side Flash object, because this was written well before WebSockets were a thing, and I've never taken the time to upgrade the code to use WebSockets instead.

**Comment by IcedEagle** [comment]
Nice, works great. Thank you!
